thresholds:
  block_illegal: 0.80
  block_extremism: 0.80
  redact_profanity: 0.65
  review_band_low: 0.50
  review_band_high: 0.80

features:
  use_ml: true
  normalize_to: "cyr"
  allow_unidecode: true
  keep_logging_matches: true

redaction:
  placeholder: "[REDACTED]"
  strict_terms_only: true
